### ISSUE TITLE
NetApiHelpers flush override error

### ISSUE THREAD

**Issue by Vildan** [JAndrassy/TelnetStream#37]
Error when compiling 1.3.0 version. 
.pio/libdeps/esp32dev/NetApiHelpers/src/ServerTemplate.h:118:16: error: 'void ServerTemplate<TServer, TClient>::flush() [with TServer = WiFiServer; TClient = WiFiClient]' marked 'override', but does not override
it was not there on 1.2.4 version.

**Comment by Vildan** [comment]
ESP32 board

**Comment by JAndrassy** [comment]
what version of ESP32 core?

**Comment by Vildan** [comment]
[env:cube1]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DHARDWARE_CUBE1
			  -D PIO_ENV_NAME=\"${PIOENV}\"
board_build.partitions = default.csv
monitor_speed = 115200
extra_scripts = post_build_script.py
lib_deps = 
	...
	jandrassy/TelnetStream@^1.3.0

**Comment by JAndrassy** [comment]
what version of the esp32 core do you have installed?
only old versions before 2.0.3 from May 2022 don't have flush() in Print

**Comment by Vildan** [comment]
After updating platform Espressif 32 from 3.1.0 version to 6.4.0 version, it start compiling without the problem. Thank you

**Comment by JAndrassy** [comment]
that is the platformio versions numbering, not the normal one
